# Generated by Django 3.1.8 on 2021-04-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_msg', models.TextField()),
                ('end_msg', models.TextField()),
                ('count_to', models.CharField(max_length=100)),
            ],
        ),
    ]
